/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/bar': RouteRecordInfo<
      '/bar',
      '/bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bookmarks': RouteRecordInfo<
      '/bookmarks',
      '/bookmarks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat-zh': RouteRecordInfo<
      '/chat-zh',
      '/chat-zh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/giving-talks': RouteRecordInfo<
      '/giving-talks',
      '/giving-talks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/podcasts': RouteRecordInfo<
      '/podcasts',
      '/podcasts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/streams': RouteRecordInfo<
      '/streams',
      '/streams',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/talks': RouteRecordInfo<
      '/talks',
      '/talks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use': RouteRecordInfo<
      '/use',
      '/use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/bar.md': {
      routes:
        | '/bar'
      views:
        | never
    }
    'pages/bookmarks.md': {
      routes:
        | '/bookmarks'
      views:
        | never
    }
    'pages/chat.md': {
      routes:
        | '/chat'
      views:
        | never
    }
    'pages/chat-zh.md': {
      routes:
        | '/chat-zh'
      views:
        | never
    }
    'pages/demos.md': {
      routes:
        | '/demos'
      views:
        | never
    }
    'pages/giving-talks.md': {
      routes:
        | '/giving-talks'
      views:
        | never
    }
    'pages/media.md': {
      routes:
        | '/media'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/podcasts.md': {
      routes:
        | '/podcasts'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
    }
    'pages/streams.md': {
      routes:
        | '/streams'
      views:
        | never
    }
    'pages/talks.md': {
      routes:
        | '/talks'
      views:
        | never
    }
    'pages/use.md': {
      routes:
        | '/use'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
